### ISSUE TITLE
Desktop App

### ISSUE THREAD

**Issue by trymeouteh** [iancoleman/slip39#17]
Please make this into a simple electron desktop app which can be downloaded on Windows, Mac and Linux (AppImage, Debian Repo, Arch Repo) with a SHA256 signatures to ensure it is secure. This way no need to trust the website if it is compromised and can be used offline.

**Comment by iancoleman** [comment]
You can browse to the page https://iancoleman.io/slip39 and down the page (File > Save). Or build it from the source if you don't trust the site.

This file can then be used offline in any browser. No need for electron.

I haven't done signed sha256 hashes for this particular tool since it's just a prototype, but I do for bip39.
